---
title: "EDA"
author: "Yuying Lu"
date: "2024-09-26"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = F, warning = F)
```

```{r}
library(tidyverse)
library(ggridges)
```


Import the weather data

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USW00022534", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2021-01-01",
    date_max = "2022-12-31") |>
  mutate(
    name = case_match(
      id, 
      "USW00094728" ~ "CentralPark_NY", 
      "USW00022534" ~ "Molokai_HI",
      "USS0023B17S" ~ "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10,
    month = lubridate::floor_date(date, unit = "month")) |>
  select(name, id, everything())

weather_df
```

```{r}
weather_df |> 
  ggplot(aes(x = prcp)) + 
  geom_histogram()
```

```{r}
weather_df |> 
  filter(prcp >= 1000)
```

```{r}
weather_df |> 
  filter(tmax >= 20, tmax <= 30) |> 
  ggplot(aes(x = tmin, y = tmax, color = name, shape = name)) + 
  geom_point(alpha = .75)
```


## Group_by

```{r}
weather_df |> 
  group_by(name)
```

```{r}
weather_df |> 
  group_by(name) |> summarise(n_obs = n(),
                              n_dist = n_distinct(month))
```

```{r}
weather_df |> 
  group_by(name, month) |> summarise(n_obs = n())
```

```{r}
weather_df |> 
  count(name)
```


```{r}
weather_df |> 
  drop_na(tmax) |> 
  mutate(
    cold = case_when(
      tmax < 5 ~ 'cold',
      tmax >= 5 ~ 'not_cold'
    )
  ) |> 
  group_by(name, cold) |> 
  summarize(count = n())
```
```{r}
weather_df |> 
  drop_na(tmax) |> 
  mutate(
    cold = case_when(
      tmax < 5 ~ 'cold',
      tmax >= 5 ~ 'not_cold'
    )
  ) |> 
  janitor::tabyl(name, cold)
```

## General 

Let't try some other useful summaries

```{r}
weather_df |> 
  group_by(name, month) |> 
  summarize(
    mean_tmax = mean(tmax, na.rm = TRUE),
    median_tmin = median(tmin, na.rm = TRUE),
    sd_prop = sd(prcp, na.rm = TRUE)
  )
```

summarize and then plot ...

```{r}
weather_df |> 
  group_by(name, month) |> 
  summarize(
    mean_tmax = mean(tmax, na.rm = TRUE),
    median_tmin = median(tmin, na.rm = TRUE),
    sd_prop = sd(prcp, na.rm = TRUE)
  ) |> 
  ggplot(aes(x = month, y = mean_tmax, color = name))+
  geom_point() +
  geom_line()
```


format for readers

```{r}
weather_df |> 
  group_by(name, month) |> 
  summarize(
    mean_tmax = mean(tmax, na.rm = TRUE)
  ) |> 
  pivot_wider(
    names_from = name,
    values_from = mean_tmax) |> 
  knitr::kable(digits = 3,
               col.names = c('Month', 'Central Park', 'Molokai', 'Waterhole'))

```

## grouped mutates

```{r}
weather_df |> 
  group_by(name) |> 
  mutate(mean_tmax = mean(tmax, na.rm = TRUE),
         centered_tmax = tmax - mean_tmax) |> 
  ggplot(aes(x = date, y = centered_tmax, color = name)) + 
  geom_point()
```

Find hottest / coldest days.

```{r}
weather_df |> 
  group_by(name) |> 
  mutate(
    temp_rank = min_rank(tmax)
  ) |> 
  filter(temp_rank < 3)
```

```{r}
weather_df |> 
  group_by(name) |> 
  filter(min_rank(tmax) < 4)
```

```{r}
weather_df |> 
  group_by(name) |> 
  filter(min_rank(tmax) < 4) |> 
  arrange(desc(tmax))
```



```{r}
weather_df |> 
  group_by(name) |> 
  mutate(
    lagged_temp = lag(tmax)
  ) 
```





