---
title: "vis_1"
author: "Yuying Lu"
date: "2024-09-26"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggridges)
```

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USW00022534", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2021-01-01",
    date_max = "2022-12-31") |>
  mutate(
    name = case_match(
      id, 
      "USW00094728" ~ "CentralPark_NY", 
      "USW00022534" ~ "Molokai_HI",
      "USS0023B17S" ~ "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) |>
  select(name, id, everything())

```

```{r}
weather_df
```

```{r}
weather_df |>
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point()
```

## Advanced Plot

```{r, fig.width= 8, fig.height= 6}
ggplot(weather_df, aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name), alpha = .5) +
  geom_smooth(se = FALSE)
```


```{r, fig.width= 8, fig.height= 6}
ggplot(weather_df, aes(x = tmin, y = tmax,color = name)) + 
  geom_point( alpha = .5) +
  geom_smooth(se = FALSE)
```


```{r, fig.width= 12, fig.height= 4}
ggplot(weather_df, aes(x = tmin, y = tmax,color = name)) + 
  geom_point( alpha = .5) +
  geom_smooth(se = FALSE) +
  facet_grid(. ~ name)
```




Let's make somewhat interesting scatterplot.

```{r, fig.width= 12, fig.height= 5}
weather_df |> 
  ggplot(aes(x = date, y= tmax, color = name, size = prcp))+
  geom_point(alpha=.3) +
  geom_smooth(se = FALSE) +
  facet_grid(. ~ name)
```

```{r}
weather_df |> 
  filter(name == 'CentralPark_NY') |> 
  pivot_longer(tmax:tmin,
               names_to = 'type',
               values_to = 'temp') |> 
  mutate(temp= temp * ( 9 / 5 ) + 32) |> 
  ggplot(aes(x = date, y = temp, color = type))+
  geom_point(alpha=.3)+
  geom_smooth(se = FALSE)
```


```{r}
weather_df |> 
  filter(name == 'CentralPark_NY') |> 
  mutate(tmax_f= tmax * ( 9 / 5 ) + 32,
         tmin_f= tmin * ( 9 / 5 ) + 32) |> 
  ggplot(aes(x = tmax_f, y = tmin_f))+
  geom_point(alpha=.3)+
  geom_smooth(method = "lm", se = FALSE)
```

```{r}
weather_df |> 
  ggplot(aes(x = tmin, y = tmax))+
  geom_hex()
```

```{r}
weather_df |> 
  ggplot(aes(x = tmin, y = tmax)) +
  geom_point(color = "blue")
```

```{r}
weather_df |> 
  ggplot(aes(x = tmin)) +
  geom_histogram()
```

```{r}
weather_df |> 
  ggplot(aes(x = tmin, fill= name)) +
  geom_histogram()
```

```{r}
weather_df |> 
  ggplot(aes(x = tmin, fill= name)) +
  geom_histogram(position = "dodge")
```


How do I fix this?

```{r, fig.width= 12, fig.height= 5}
weather_df |> 
  ggplot(aes(x = tmin, fill = name)) +
  geom_histogram() +
  facet_grid(. ~ name)
```

Maybe a density plot?

```{r}
weather_df |> 
  ggplot(aes(x = tmin, color = name, fill = name)) + 
  geom_density(alpha = .3)
```


Box-Plot

```{r}
weather_df |> 
  ggplot(aes(x = name, y= tmin, fill = name))+
  geom_boxplot()
```


```{r}
weather_df |> 
  ggplot(aes(x = name, y= tmin, fill = name))+
  geom_violin(alpha = .8)
```


Ridge Plot

```{r, fig.width= 8, fig.height==8}
weather_df |> 
  ggplot(aes(x = tmin, y = name)) + 
  geom_density_ridges(aes(fill = name), alpha =.7, color = 'grey')
```


```{r}
weather_df |> 
  ggplot(aes(x = name, y = prcp, fill= name))+
  geom_boxplot(outliers = FALSE)
```


```{r}
weather_df |> 
  ggplot(aes(x = name, y = prcp, fill= name))+
  geom_violin()
```

```{r}
weather_df |> 
  ggplot(aes(y = name, x = prcp))+
  geom_density_ridges(aes(fill = name), alpha =.7, color = 'grey')
```


```{r}
weather_df |> 
  ggplot(aes(y = prcp))+
  geom_density(aes(fill = name), alpha =.7, color = 'grey')
```


```{r}
ggp_weather = 
  weather_df |> filter(prcp > 10 , prcp < 1000) |> 
    ggplot(aes(x = prcp, fill = name, color = name)) + 
    geom_density(alpha = .3)

ggsave("ggp_weather.pdf", ggp_weather, width = 8, height = 6)
```







```{r}

```

